version: '3'

services:
  mongodb:
    image: nonoroazoro/rpi-mongo:latest

  backend:
    environment:
      - SERVER_ADDRESS=${SERVER_ADDRESS}
    build: ./back-end
    depends_on:
      - "mongodb"
    volumes:
      - ./back-end/api:/app/api
    ports:
      - 3001:3001

  frontend:
    environment:
      - SERVER_ADDRESS=${SERVER_ADDRESS}
    build: ./front-end
    volumes:
      - ./front-end/src:/app/src
    ports:
      - 80:80
